blank_issues_enabled: true
contact_links:
  - name: MMRL Telegram group
    url: https://t.me/RepoLoader
    about: Join the oficial MMRL group and discuss with the developers and other community member.
  - name: Fox2Code Telegram group
    url: https://t.me/Fox2Code_Chat
    about: Join the Telegram group if you want to discuss with the community.
